server:
  port: 8085

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  main:
    allow-circular-references: true


  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/movie?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
      username: root
      password: 200318
      validation-query: SELECT 1
      test-on-borrow: true

  redis:
    port: 6379
    host: 127.0.0.1
    timeout: 3000
    jedis:
      pool:
        max-active: 8
        max-wait: 2000
        max-idle: 8
        min-idle: 0
        time-between-eviction-runs: 1000
#    lettuce:
#      pool:
#        min-idle: 5
#        max-idle: 10
#        max-wait: -1


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-column-underline: true
